export const GET_PRODUCT_LIST_START="GET_PRODUCT_LIST_START"
export const GET_PRODUCT_LIST_SUCCESS="GET_PRODUCT_LIST_SUCCESS"
export const GET_PRODUCT_LIST_ERROR="GET_PRODUCT_LIST_ERROR"



//========================
export const GET_USER_START="GET_USER_START"
export const GET_USER_SUCCESS="GET_USER_SUCCESS"
export const GET_USER_ERROR="GET_USER_ERROR"

